--from animal.sql
ALTER TABLE ANIMAL
	ADD FOREIGN KEY (species_ID) REFERENCES SPECIES(species_ID),
	ADD FOREIGN KEY (enclosure_ID) REFERENCES ENCLOSURE(enclosure_ID);

--from attraction.sql
ALTER TABLE ATTR_ANIMAL
	ADD FOREIGN KEY (animal_ID) REFERENCES ANIMAL (animal_ID),
    ADD FOREIGN KEY (attr_ID) REFERENCES ATTRACTION (attr_ID);

ALTER TABLE ATTR_TICKET
	ADD FOREIGN KEY (ticket_ID) REFERENCES TICKET (ticket_ID),
    ADD FOREIGN KEY (attr_ID) REFERENCES ATTRACTION (attr_ID);

--employee
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (department_ID) REFERENCES EMPLOYEE (department_ID);

--feeding.sql
ALTER TABLE FEEDING ADD FOREIGN KEY (food_ID) REFERENCES FEED_ITEM (food_ID);

--FOOD_STALL.sql
ALTER TABLE FOOD_STALL ADD FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID);

---GIFT_SHOP.sql
ALTER TABLE GIFT_SHOP ADD FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID);

--medical_records.sql
ALTER TABLE medical_records
	ADD FOREIGN KEY(animal_ID) REFERENCES ANIMAL(animal_ID),
	ADD FOREIGN KEY (vet_ID) REFERENCES EMPLOYEE(employee_ID);

-- menu_item.SQL
ALTER TABLE menu_item ADD FOREIGN KEY (stall_ID) REFERENCES FOOD_STALL(stall_ID);

-- PARKING_LOT.SQL
alter table PARKING_LOT add FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID);
--parking_sessions.SQL
ALTER TABLE parking_sessions ADD FOREIGN KEY (lot_ID) REFERENCES PARKING_LOT(lot_ID);

--PRODUCT.SQL
ALTER TABLE PRODUCT ADD FOREIGN KEY (shop_ID) REFERENCES GIFT_SHOP(shop_ID);

--VISITORS.SQL
ALTER TABLE VISITORS ADD FOREIGN KEY(ticket_ID) REFERENCES TICKET(ticket_ID);
