--from animal.sql
ALTER TABLE ANIMAL
	ADD FOREIGN KEY (species_ID) REFERENCES SPECIES(species_ID),
	ADD FOREIGN KEY (enclosure_ID) REFERENCES ENCLOSURE(enclosure_ID);

--from attraction.sql
ALTER TABLE ATTR_ANIMAL
	ADD FOREIGN KEY (animal_ID) REFERENCES ANIMAL (animal_ID),
    ADD FOREIGN KEY (attr_ID) REFERENCES ATTRACTION (attr_ID);

ALTER TABLE ATTR_TICKET
	ADD FOREIGN KEY (ticket_ID) REFERENCES TICKET (ticket_ID),
    ADD FOREIGN KEY (attr_ID) REFERENCES ATTRACTION (attr_ID);


  --FOREIGN KEY (food_ID) REFERENCES FEED_ITEM (food_ID)
  --FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID)
    --FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID)
    --FOREIGN KEY(animal_ID) REFERENCES ANIMAL(animal_ID),
    --FOREIGN KEY (vet_ID) REFERENCES EMPLOYEE(employee_ID)
    --   --FOREIGN KEY (stall_ID) REFERENCES FOOD_STALL(stall_ID)
    --   --FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID)
    --   --FOREIGN KEY (lot_ID) REFERENCES PARKING_LOT(lot_ID)
    --FOREIGN KEY (shop_ID) REFERENCES GIFT_SHOP(shop_ID)
 --FOREIGN KEY(ticket_ID) REFERENCES TICKET(ticket_ID)
