-- i noted the files i copied from
-- commenting out unmade tables
-- from animal.sql
ALTER TABLE ANIMAL
	ADD FOREIGN KEY (species_ID) REFERENCES SPECIES(species_ID),
	ADD FOREIGN KEY (enclosure_ID) REFERENCES ENCLOSURE(enclosure_ID);

-- from attraction.sql
ALTER TABLE ATTR_ANIMAL
	ADD FOREIGN KEY (animal_ID) REFERENCES ANIMAL (animal_ID),
    ADD FOREIGN KEY (attr_ID) REFERENCES ATTRACTION (attr_ID);

ALTER TABLE ATTR_TICKET
	ADD FOREIGN KEY (ticket_ID) REFERENCES TICKET (ticket_ID),
    ADD FOREIGN KEY (attr_ID) REFERENCES ATTRACTION (attr_ID);

-- feeding.sql
ALTER TABLE FEEDING
	ADD FOREIGN KEY (food_ID) REFERENCES FEED_ITEM (food_ID),
	ADD FOREIGN KEY (animal_ID) REFERENCES ANIMAL(animal_ID);

-- FOOD_STALL.sql
ALTER TABLE FOOD_STALL ADD FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID);

-- GIFT_SHOP.sql
ALTER TABLE GIFT_SHOP ADD FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID);

-- medical_records.sql
ALTER TABLE MEDICAL_RECORD
	ADD FOREIGN KEY(animal_ID) REFERENCES ANIMAL(animal_ID),
	ADD FOREIGN KEY (vet_ID) REFERENCES EMPLOYEE(employee_ID);

-- menu_item.SQL
ALTER TABLE MENU_ITEM ADD FOREIGN KEY (stall_ID) REFERENCES FOOD_STALL(stall_ID);

-- PARKING_LOT.SQL
alter table PARKING_LOT add FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID);
-- parking_sessions.SQL
ALTER TABLE PARKING_SESSION ADD FOREIGN KEY (lot_ID) REFERENCES PARKING_LOT(lot_ID);

-- PRODUCT.SQL
ALTER TABLE PRODUCT ADD FOREIGN KEY (shop_ID) REFERENCES GIFT_SHOP(shop_ID);

-- VISITOR.SQL
ALTER TABLE VISITOR ADD FOREIGN KEY(ticket_ID) REFERENCES TICKET(ticket_ID);

-- enclosure.SQL managed by what dept relation
ALTER TABLE ENCLOSURE ADD FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID);

-- under what dept relation
ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (department_ID) REFERENCES DEPARTMENT(department_ID),
	ADD FOREIGN KEY (manager_ID) REFERENCES EMPLOYEE(employee_ID) ON DELETE SET NULL;

-- from animal care
ALTER TABLE ANIMAL_CARE
	ADD FOREIGN KEY (animal_ID) REFERENCES ANIMAL(animal_ID) ON DELETE CASCADE,
	ADD FOREIGN KEY (employee_ID) REFERENCES EMPLOYEE(employee_ID) ON DELETE CASCADE;

-- CUST_TRANSACTION.SQL
ALTER TABLE CUST_TRANSACTION ADD FOREIGN KEY (visitor_ID) REFERENCES VISITOR(visitor_ID) ON DELETE RESTRICT;

-- TRANSACTION_ITEM.SQL
ALTER TABLE TRANSACTION_ITEM ADD FOREIGN KEY (transaction_ID) REFERENCES CUST_TRANSACTION(transaction_ID) ON DELETE CASCADE;

-- DONATION.SQL
ALTER TABLE DONATION
	ADD FOREIGN KEY (donor_ID) REFERENCES donor(donor_ID) ON DELETE RESTRICT;

-- frm membership.SQL
ALTER TABLE VISITOR(
	ADD FOREIGN KEY (visitor_id) REFERENCES MEMBERSHIP(visitor_ID) ON DELETE CASCADE;
);
-- using an fk so we dont enforce vistors to only have one id
ALTER TABLE TICKET
	ADD FOREIGN KEY (visitor_ID) REFERENCES VISITOR(visitor_ID);
